# Build options
source: ./app/jekyll
destination: ./app/assets
timezone: "Europe/Paris"
encoding: "utf-8"
markdown: kramdown

# Site settings
title: Roleplay
description: "Version audio de nos parties de jeu de rôle"
baseurl: "/roleplay.pixelastic.com"
url: "http://roleplay.pixelastic.com"
repository: "https://github.com/pixelastic/meetups.pixelastic.com"
