#!/usr/bin/env bash
base_dir=$(pwd)

# Install Jekyll and Ruby dependencies
bundle install

# Init Bourbon, Neat and Bittes
cd ./app/styles/vendors
bundle exec bourbon install
bundle exec neat install
bundle exec bitters install

# Make normalize.css importable
cd "$base_dir"
cp ./node_modules/normalize.css/normalize.css ./node_modules/normalize.css/normalize.scss
