#!/usr/bin/env bash
base_dir=$(pwd)

Install Jekyll and Ruby dependencies
bundle install

css_vendors=./app/styles/vendors
mkdir -p $css_vendors

# Init Bourbon, Neat and Bitters
cd ./app/styles/vendors
bundle exec bourbon install
bundle exec neat install
bundle exec bitters install

# Make normalize.css importable
cd "$base_dir"
css_vendors=./app/styles/vendors

mkdir -p $css_vendors/normalize && \
cp ./node_modules/normalize.css/normalize.css $css_vendors/normalize/normalize.scss && \
echo "Add normalize to scss vendors"

# Make font awesome importable
mkdir -p $css_vendors/font-awesome && \
cp -r ./node_modules/font-awesome/scss/* $css_vendors/font-awesome && \
echo "Add font-awesome to scss vendors"

mkdir -p ./app/jekyll/fonts/font-awesome && \
cp -r ./node_modules/font-awesome/fonts/* ./app/jekyll/fonts/font-awesome && \
echo "Add font-awesome font to /fonts"

