#!/usr/bin/env zsh
# I write posts using Typora (for the ease of use of copy-pasting images), but
# there is some cleanup needed once done, especially in regard with the images
set -e

local folder="$1"

if [[ $folder == "" ]]; then
	echo "You must pass the folder to clean as an argument"
	exit 1
fi

cd $folder

# Rename all jpeg to jpg
function renameJpegToJpg() {
  local jpegFiles=(*.jpeg(N))
  rename 's/.jpeg/.jpg/g' $jpegFiles
}

# Rename all pictures so their name does not contain any spaces
function removeSpacesFromImageNames() {
  local imageFiles=(*.{jpg,png,gif}(N))
  rename 's/ //g' $imageFiles
}

renameJpegToJpg
removeSpacesFromImageNames



