#!/usr/bin/env bash
set -e

# Make normalize.css importable
css_vendors=./source/css/_vendors

mkdir -p $css_vendors/normalize
cp \
	./node_modules/normalize.css/normalize.css \
	$css_vendors/normalize/normalize.scss

echo "Add normalize to scss vendors"
